### ISSUE TITLE
Need more left/right data

### ISSUE THREAD

**Issue by giangngt** [nolanspecter/Hand-Gesture#1]
Take your own pics with left/right hand gesture, label it.

**Comment by nolanspecter** [comment]
I finished mine. Trying to get outsoure help

**Comment by giangngt** [comment]
Resolve with 640162c7707f13063e74ed5f9d9196dea1d7f0bd, d9501ea437bce51abc099e4fa0d814ed4d908f05, bd70a0c37de45b3735dedf161c5ba50216ce9d9a
